name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install dependencies
        working-directory: src
        run: bun i

      - name: Build Astro
        working-directory: src
        run: bun run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: tokutei-v3-web
          entrypoint: server/entry.mjs
          root: src/dist